spring.application.name=${SPRING_APPLICATION_NAME:DentalClinic}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.H2Dialect}

spring.h2.console.enabled=${SPRING_H2_CONSOLE_ENABLED:true}
spring.h2.console.path=${SPRING_H2_CONSOLE_PATH:/h2-console}

server.port=${PORT:10000}
server.address=0.0.0.0
server.servlet.session.timeout=${SERVER_SERVLET_SESSION_TIMEOUT:5h}

# Twilio
twilio.account.sid=${TWILIO_ACCOUNT_SID}
twilio.auth.token=${TWILIO_AUTH_TOKEN}
twilio.whatsapp.from=${TWILIO_WHATSAPP_FROM}
twilio.phone.number=${TWILIO_PHONE_NUMBER}
twilio.whatsapp.template.fileShare=${TWILIO_WHATSAPP_TEMPLATE_FILESHARE}
twilio.whatsapp.template.appointmentUpdate=${TWILIO_WHATSAPP_TEMPLATE_APPOINTMENTUPDATE}
